### 5.1. Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])

c = a + b
print(c)

[ 4  6  8 10]


In [3]:
c = np.add(a, b)
print(c)

[ 4  6  8 10]


In [4]:
d = a*b
print(d)

[ 0  5 12 21]


In [5]:
d = a.dot(b)
print(d)

z = np.dot(a,b)
print(z)

38
38


### Вычислите, по возможности не используя программирование: (5E)-1 где Е – единичная матрица размера 5х5.

Если единичную матрицу размера 5 на 5 умножить на 5, то вместо единиц будут 5-ки по диагонали. Соответственно в обратной матрице или в степени -1 они (5-ки) меняются на 0,2 (= 1 / 5)

### 5.2. Вычислите определитель

In [6]:
a = np.array([[1, 2, 3],
              [4, 0, 6],
              [7, 8, 9]])
print(a)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [7]:
detA = 1*(0*9 - 6*8) - 2*(4*9 - 6*7) + 3*(4*8 - 0*7)
print(detA)

60


In [8]:
np.linalg.det(a)

59.999999999999986

### 5.3.1.  Вычислите матрицу, обратную данной:

In [9]:
a = np.array([[1, 2, 3],
              [4, 0, 6],
              [7, 8, 9]])
print(a)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [10]:
M = np.array([[0*9-6*8, 4*9-6*7, 4*8-0*7],
              [2*9-3*8, 1*9-3*7, 1*8-2*7],
              [2*6-0*3, 1*6-4*3, 1*0-2*4]])
print(M)

[[-48  -6  32]
 [ -6 -12  -6]
 [ 12  -6  -8]]


In [11]:
A = np.array([[-48, 6, 32], [6, -12, 6], [12, 6, -8]])

In [19]:
At = A.transpose()
A_1 = At/60
print(A_1.dot(a))

[[ 1.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


### 5.3.1. Приведите пример матрицы 4х4, ранг которой равен 1.

In [35]:
b = np.array([[1, 1, 1, 1],
              [0, 0, 0, 0],
              [0, 0, 0, 0],
              [1, 1, 1, 1]])
np.linalg.matrix_rank(b, 0.00001)

1

### 5.4. Вычислите скалярное произведение двух векторов:  
- (1, 5)  и  (2, 8)

In [37]:
a = np.array([1, 5])
b = np.array([2, 8])
np.inner(a, b)

42

### 5.5.  Вычислите смешанное произведение трех векторов:
- (1, 5, 0), (2, 8, 7) и (7, 1.5, 3)

In [39]:
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)

v = np.cross(a, b)
print(np.inner(v, c))

v_1 = np.cross(b, c)
print(np.inner(v_1, a))

228.5
228.5
